### ISSUE TITLE
Viewport black at startup until after resizing window

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/studio#11]
from https://github.com/exokitxr/exokit/pull/1002#issuecomment-492787368

viewport is black at startup until after resizing window [see video demo here](https://cdn.discordapp.com/attachments/573306250142416896/579146197139456011/2019-05-17_22-19-32.mp4)
    - [one hint is possible a depth buffer being initialized, or not](https://github.com/exokitxr/exokit/blob/4b42fd4739382dfaa028beeae5fb2abe51724ace/deps/exokit-bindings/windowsystem/src/windowsystem.cc#L376)

**Comment by modulesio** [comment]
Does this still reproduce with https://github.com/exokitxr/exokit/pull/1187?

**Comment by chrisplatorres** [comment]
![greenstudioCapture](https://user-images.githubusercontent.com/29695350/59164919-2bddc000-8ad9-11e9-817c-350adeaf89d2.PNG)

still getting on https://github.com/exokitxr/exokit/pull/1187

**Comment by modulesio** [comment]
Should be fixed now.

**Comment by chrisplatorres** [comment]
fixed by https://github.com/exokitxr/exokit/commit/1e982526b74b590bb4d054e280202d38c11dd5db
