### ISSUE TITLE
Opening dropdown menus makes viewport black

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/studio#12]
from https://github.com/exokitxr/exokit/pull/1002#issuecomment-492787368

Opening any of the dropdown menus makes the viewport black, maybe there is some alternative to just show "screenshots" of the viewport/engine render?

![layCapture](https://user-images.githubusercontent.com/29695350/57802552-d998c180-771b-11e9-886d-e1142abca2ea.PNG)

**Comment by modulesio** [comment]
This is deliberately not rendered while you have a menu open, because we do not depth-composite the 2D UI and the 3D. It can be done with a shader or stencil, though at that point it brings exokit close to being burdened with 2d browser concerns.

**Comment by modulesio** [comment]
I think I have a solution for this: we can use a green screen and a shader to composite.
