### ISSUE TITLE
Studio loads upside down and without UI occasionally

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/studio#13]
from: https://github.com/exokitxr/exokit/pull/1002#issuecomment-493802539

~10% ? of times studio loads upside down and without UI
  
 

![25Capture](https://user-images.githubusercontent.com/29695350/57989843-5c948180-7a66-11e9-931e-6cd9e77c86b1.PNG)

> it's what I think I mentioned before, the CEF mode being unsupported, since we do in-process it's probably a race condition in the boot it especially triggers if you jiggle the mouse, the first thing to try would be to break it out to the supported multiprocess fork

**Comment by modulesio** [comment]
I think this should be completely fixed with https://github.com/exokitxr/exokit/pull/1187.

**Comment by chrisplatorres** [comment]
This has been fixed since https://github.com/exokitxr/exokit/pull/1187.
