### ISSUE TITLE
Not able to resize drag over viewport

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/studio#26]
This issue is to fix not being able to resize drag over the viewport/engine render. (mentioned here: https://github.com/exokitxr/studio/pull/24#issuecomment-500277097)

visual reference gif:
![studioconsolecss3](https://user-images.githubusercontent.com/29695350/59170150-f77ef980-8b02-11e9-9619-30e3fb1f48b9.gif)

**Comment by chrisplatorres** [comment]
The workaround so far has to click and then drag over a non-viewport/UI section like the sidebar to register the drag.

**Comment by modulesio** [comment]
Is this a PR or an issue?

**Comment by chrisplatorres** [comment]
> Is this a PR or an issue?

got ahead of myself, updated

**Comment by modulesio** [comment]
The bug is here: https://github.com/exokitxr/studio/blob/d6c8f51a971256768685eef0c92b0838f370036f/index.html#L1352
