### ISSUE TITLE
reality tab load error: hello_ml.html because the repo is missing the file

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/studio#28]
We are getting the error `reality tab load error: hello_ml.html` when loading the template in dropdown because there is not a hello_ml.html in the repo.

https://github.com/exokitxr/studio/blob/master/ui/src/components/Engine.jsx#L291
https://github.com/exokitxr/studio/blob/master/index.html#L25

**Comment by modulesio** [comment]
Probably best to delete that one.
