### ISSUE TITLE
Changing width/height settings behavior

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/studio#36]
Currently when changing width/height settings behavior, it does not resize the rest of the window to match:

![changwhCapture](https://user-images.githubusercontent.com/29695350/59324036-d7863c00-8ca2-11e9-8cd8-c1f40ef6e613.PNG)

**Comment by chrisplatorres** [comment]
Perhaps the behavior here should be resizing the entire window to fit the new viewport size.

**Comment by chrisplatorres** [comment]
Notes from Discord:

> correct would be the headset view fills the viewport as always
> it might be crisper/non-crisper depending on the res you set
> but it should still fill the window
> from the above it looks like the blit metrics are not correct

**Comment by modulesio** [comment]
Should be working find in the new composure:

![Capture 27](https://user-images.githubusercontent.com/6926057/59555569-5e6c3a80-8f69-11e9-841a-97b1b927117b.PNG)
